figav03:	figa_main.o figa.o common.o nstr.o
		g++ figa_main.o figa.o common.o nstr.o -o figav03

figa_main.o:	figa_main.cc
		g++ -c figa_main.cc

figa.o:		figa.cc figa.h
		g++ -c figa.cc

common.o:	common.cc common.h
		g++ -c common.cc

nstr.o:		nstr.cc nstr.h
		g++ -c nstr.cc
