#!/usr/bin/python

import re
import sys

dict = {}
file = open(sys.argv[1],'r')
#line = file.readline()
#if line == '':
#  exit()
#line = line.split('\n')
#split = line[0].split('\t')
#last = split[0]
#print last + '\t' + split[1] + '\t' + split[2]
while True:
  line = file.readline()
  if line == '':
    exit()
  line = line.split('\n')
  split = line[0].split('\t')
  if split[0] not in dict.keys():
    dict[split[0]] = 1
    print split[0] + '\t' + split[1] + '\t' + split[2]  + '\t' + split[3]  + '\t' + split[4] 
 
